version: 2

models:
  - name: customers
    description: 顧客ごとに1レコードを持つ
    columns:
      - name: customer_id
        description: 顧客ID PK
        data_type: INT64
        tests:
          - unique
          - not_null
      - name: first_name
        description: 名
        data_type: STRING
      - name: last_name
        description: 姓
        data_type: STRING
      - name: first_order_date
        description: 初回注文日
        data_type: DATE
      - name: most_recent_order_date
        description: 最近の注文
        data_type: DATE
      - name: number_of_orders
        description: 注文数
        data_type: INT64
  - name: stg_customers
    columns:
      - name: customer_id
        description: 顧客ID PK
        data_type: INT64
        tests:
          - unique
          - not_null
  - name: stg_orders
    columns:
      - name: order_id
        description: 注文ID PK
        data_type: INT64
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
